# Generated by Django 3.2 on 2022-03-07 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_admin', '0003_book'),
        ('my_book', '0002_alter_userinfo_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnum', models.IntegerField()),
                ('sumprice', models.CharField(max_length=64)),
                ('time', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_cart', to='my_admin.book')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo_cart', to='my_book.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PayCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carttopay', to='my_shopcar.cart')),
            ],
        ),
        migrations.CreateModel(
            name='myorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.CharField(max_length=32)),
                ('allprice', models.FloatField()),
                ('allpnum', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_order', to='my_admin.book')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo_order', to='my_book.userinfo')),
            ],
        ),
    ]
