# Generated by Django 3.2 on 2022-03-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shopcar', '0002_remove_myorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='static',
            field=models.CharField(default='待支付', max_length=10),
        ),
    ]
