# Generated by Django 3.2 on 2022-03-23 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_shopcar', '0003_myorder_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='paydate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
