# Generated by Django 3.2 on 2022-03-02 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=128)),
                ('get_name', models.CharField(max_length=128)),
                ('get_phone', models.CharField(max_length=128)),
                ('get_code', models.CharField(max_length=128)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo_address', to='my_book.userinfo')),
            ],
        ),
    ]
